### ISSUE TITLE
Often the selected PS and its PA are overlapped

### ISSUE THREAD

**Issue by melish** [EEA-Norway-Grants/dataviz#111]
![image](https://user-images.githubusercontent.com/1218168/27074652-71a6c126-5030-11e7-8e6b-7350ebf7716e.png)
In this example the active filters are FM: EEA Grants, PS: Human and social development

Only 3/5 PA are visible in the pie chart. The big slice represents the parent PS

**Comment by xlotlu** [comment]
related to #87 and #98. there should be one fix to rule them all.
