### ISSUE TITLE
Data import - NUTS codes issue for Croatia

### ISSUE THREAD

**Issue by melish** [EEA-Norway-Grants/dataviz#134]

**Comment by melish** [comment]
![image](https://user-images.githubusercontent.com/1218168/27261601-e04a1340-544e-11e7-81b2-0fe4ea3cb3e1.png)

**Comment by xlotlu** [comment]
issue resurfaced, but on projects scenario only: data has codes HR04, while map level 2 has code HR02.

**Comment by melish** [comment]
Manually edited map. There is a small bug on the western border, but need a proper geojson editor to fix that.
