### ISSUE TITLE
Our Projects - When hovering on a news item, show it on the map

### ISSUE THREAD

**Issue by melish** [EEA-Norway-Grants/dataviz#155]
based on the NUTS code of the project (or the country of the project when the map is not zoomed)

**Comment by xlotlu** [comment]
either cross-component communication (nice), or brute-force, news writes directly to map (ugly but efficient)

**Comment by melish** [comment]
Johanna: we discussed about having an indication for the project news and decided it would not be needed. This is because at that level, the filter is already applied, meaning that the project stories wouldn´t appear unless the region has them.
