### ISSUE TITLE
sectors: visualization container should preserve height

### ISSUE THREAD

**Issue by xlotlu** [EEA-Norway-Grants/dataviz#165]
viz container should preserve the maximum height. filtering makes page elements dance around, which is very annoying.
(you can scroll the page to the bottom by repeatedly clicking on a beneficiary)

**Comment by xlotlu** [comment]
this is not the proper way to fix this. in fact it is not a fix at all: there is no guaranteed relationship between width and height, setting a fixed height for dynamic content is well, not smart, and overflow hidden is just evil.

the correct fix is to set a min-height on every legend update, that is the max between current height and previous min-height.

please revert 3d0beb8

**Comment by xlotlu** [comment]
the implementation is twice wrong, and that don't make it right. because:
a. it doesn't take into account the previous height.
b. it fails to account for the real reason why the legend might get updated, and is only run on click.

extra-comments in the commit.

**Comment by mihai-macaneata** [comment]
closed in 94ab385

**Comment by xlotlu** [comment]
weee
