### ISSUE TITLE
Internet explorer js error

### ISSUE THREAD

**Issue by melish** [EEA-Norway-Grants/dataviz#182]
1. [Vue warn]: Error in mounted hook: "TypeError: Object doesn't support property or method 'find'"
found in <Tabs><Sidebar><Root>

2. In the home page: Object doesn't support property or method 'fill'

**Comment by xlotlu** [comment]
@melish: first, they sound like different bugs, second, need more info, full stack trace / line numbers / anything.

**Comment by mihai-macaneata** [comment]
the first bug is caused by an Array.prototype.find in the nav-tabs plugin

**Comment by melish** [comment]
2. Overview.vue:227, to_zeros = new Array(to_.length).fill(0);
