### ISSUE TITLE
HomepageInfo should look good on mobile. Make it look good

### ISSUE THREAD

**Issue by mihai-macaneata** [EEA-Norway-Grants/dataviz#183]

**Comment by mihai-macaneata** [comment]
Right now I have a few mockups. I still need some visual identity guide and editable version of the logo in order to make one more porposal
![eeag-homepage-mobile5](https://user-images.githubusercontent.com/12417029/27330583-aa9badd8-55c2-11e7-8528-b5aab23c7bcd.jpg)
![eeag-homepage-mobile4](https://user-images.githubusercontent.com/12417029/27330586-aaa18a46-55c2-11e7-94b5-5f86e9bd6a21.jpg)
![eeag-homepage-mobile3](https://user-images.githubusercontent.com/12417029/27330584-aa9cf710-55c2-11e7-90e0-4b4be20e0200.jpg)
![eeag-homepage-mobile2](https://user-images.githubusercontent.com/12417029/27330585-aa9d3018-55c2-11e7-92da-7df16f91706d.jpg)
![eeag-homepage-mobile](https://user-images.githubusercontent.com/12417029/27330587-aaa2152e-55c2-11e7-9021-62333bc4aa37.jpg)

**Comment by melish** [comment]
Remember to make the project count figure smaller
