### ISSUE TITLE
fix tooltip code and CSS

### ISSUE THREAD

**Issue by melish** [EEA-Norway-Grants/dataviz#198]
* fix broken layouts because of white-space: pre in WithTooltip.vue
* switch to `dl` in tooltip template where not already done. see existing code in `tooltipTemplate`
* use javascript templates, like in `tooltipTemplate`

**Comment by xlotlu** [comment]
@mihai-macaneata other minor code quality stuff
- the "~" from span.action could be set from css, not inline
- the `X` inside the button should be a nice icon from the already-loaded glyphs
