### ISSUE TITLE
homepage chart: beneficiary labels overlap

### ISSUE THREAD

**Issue by xlotlu** [EEA-Norway-Grants/dataviz#220]
see Croatia / Cyprus

**Comment by melish** [comment]
from Johanna: Regarding Croatia/Cyprus we are fine with some resizing in order for it to look good in the current layout. So that is preferred rather than a drop down.

**Comment by xlotlu** [comment]
reopened because issue still exists after current fix (visible when filtering by FM).

suggest that current fix be reverted and the (rather complex) calculations be made that place labels properly spaced apart.
