### ISSUE TITLE
projects list: loading indicator

### ISSUE THREAD

**Issue by xlotlu** [EEA-Norway-Grants/dataviz#247]
on a slow connection there is no feedback about what is going on after clicking a programme.

the programme should "open" and display a throbber until the project list is displayed.

**Comment by melish** [comment]
and also cancel any other opening event that's in progress (to avoid race conditions on slow connections), as mentioned on #248

**Comment by mihai-macaneata** [comment]
There is no need to cancel other opening events since every component does it's call individually
