### ISSUE TITLE
Remove filters by donor and DPP when navigating to Home/Grants/Project pages

### ISSUE THREAD

**Issue by melish** [EEA-Norway-Grants/dataviz#306]

**Comment by xlotlu** [comment]
@melish maybe this should say "Remove filters from filter bar that are not applicable to current scenario"
As it's implemented now it has a few problems:
- it's inconsistent with how PS/PAs work - you still get those on homepage (which is bad?)
- the filtering gets lost when switching between scenarios, not nice
- it's implemented badly: when navigating away from Partners the filter is still in the url, but it disappears on next link
