### ISSUE TITLE
Embedding: allow users to decide if the component title is present or not

### ISSUE THREAD

**Issue by melish** [EEA-Norway-Grants/dataviz#312]

**Comment by xlotlu** [comment]
if i may say so, this is silly. the embedding site should decide whether they want the component title or not, by typing into their markup the component title, or not.

imagine the awesome features gained: they can choose their own wording, *and* the appropriate html tag. or should we provide those as embed params as well?

**Comment by melish** [comment]
ok, să poată fi trimisă valoarea titlului printr-un parametru, dar să fie folosit markup-ul nostru

**Comment by melish** [comment]
we'll just hide the title, see #318
