### ISSUE TITLE
Partners Sectors error when filtering by beneficiary

### ISSUE THREAD

**Issue by mihai-macaneata** [EEA-Norway-Grants/dataviz#345]
![12f2fc85fba93dabf6c913965447666b](https://user-images.githubusercontent.com/12417029/29661230-0cde5a4a-88cc-11e7-8f54-99bcbc6d3aa8.png)

**Comment by melish** [comment]
fixed by 9c3f5cea4dfc92a7351906bb65ec92c380e88317
