### ISSUE TITLE
uselessly huge font

### ISSUE THREAD

**Issue by xlotlu** [EEA-Norway-Grants/dataviz#350]
the change brought about by ce0aa0ac9217886e461f5275b9044a09bbb0d30b goes like this, for the gain of one icon:
```
1.7K eeag-icons.ttf
1.8K eeag-icons.woff
162K fontawesome-webfont.ttf
 96K fontawesome-webfont.woff
```

**Comment by melish** [comment]
maybe use https://icomoon.io/app/#/select and document the procedure
