### ISSUE TITLE
Search: remove kind from URL and use only view url

### ISSUE THREAD

**Issue by melish** [EEA-Norway-Grants/dataviz#366]

**Comment by andreeadima** [comment]
These too: 

- [ ] BS  is an "OR" filter
- [ ] Programme  is an "OR" filter
- [ ] Project is an "OR" filter
- [ ] move Organisation role filter above the Country
- [ ] change label: Organisation type category -> Organisation category
- [ ] change label: Organisation type -> Organisation sub category

**Comment by melish** [comment]
Not yet fixed: 
- OR filters (proper handling of facets)
-  Organisation role filter above the Country
