### ISSUE TITLE
pie chart: order of sectors and programme areas should be the one from data model (SortOrder)

### ISSUE THREAD

**Issue by melish** [EEA-Norway-Grants/dataviz#37]

**Comment by xlotlu** [comment]
closed in 55b9fef

**Comment by xlotlu** [comment]
@melish if the current behaviour is satisfactory, can we downgrade the priority for this?

**Comment by melish** [comment]
No, the current order is not correct yet. And Climate Change is missing

**Comment by xlotlu** [comment]
to be fixed together with #92, and related to #6

**Comment by melish** [comment]
Update the data model and use sector.SortOrder
