### ISSUE TITLE
fix map on Internet Explorer

### ISSUE THREAD

**Issue by melish** [EEA-Norway-Grants/dataviz#38]

**Comment by melish** [comment]
![image](https://cloud.githubusercontent.com/assets/1218168/26113182/8628e478-3a62-11e7-9ff2-d3685521ffe0.png)

**Comment by melish** [comment]
![image](https://cloud.githubusercontent.com/assets/1218168/26113223/a2a5c6e8-3a62-11e7-95e3-5ba14c44c76d.png)

**Comment by melish** [comment]
On localhost it looks different though:


![image](https://cloud.githubusercontent.com/assets/1218168/26113869/6fe1b95e-3a64-11e7-8686-78d610ed54bc.png)

**Comment by xlotlu** [comment]
Reopen. Needs more work.

**Comment by xlotlu** [comment]
@mihai-macaneata please test that this really works
