### ISSUE TITLE
css: scope component-related styles under a specific namespace

### ISSUE THREAD

**Issue by xlotlu** [EEA-Norway-Grants/dataviz#385]
we need to isolate all css that will appear on the remote site when embedded, so that it won't affect the remote layout.

the proposed implementation is to scope all styles under the `.dataviz` namespace so that:
1. the local site gets 
```html
<html class="dataviz>
```
in all templates (should be handled by simply editing `templates/base.html`)

2. the remote site content gets embedded in a 
```html
<div class="dataviz>
```
(by editing `templates/embed.js`)

3. the css that applies to both site and components will be separated into `common.css`, and given a namespace by using less. `dataviz.less` will contain:
```
.dataviz {
  @import "~normalize.css";
  @import "./common.css";
}
```

4. all component styles need to be manually edited to get a "`.dataviz`" in front. (there seems to be no easy, automated way to do this).

**Comment by xlotlu** [comment]
do note: while tackling no. 4, take a look at https://github.com/EEA-Norway-Grants/dataviz/issues/35

**Comment by mihai-macaneata** [comment]
Forgot to address 6a2af012ffee1511a1cd1a7978d705aac3c799df
