### ISSUE TITLE
js: split main.js into component-related and site-related scripts

### ISSUE THREAD

**Issue by xlotlu** [EEA-Norway-Grants/dataviz#386]
`main.js` needs to be split into what will later become different entry points for two separate bundles.
initially we just want to create 2 `.js` files:
- `dataviz.js` will contain code that is component-specific (or that is common to everything):
  - polyfills
  - Vue
  - VueSuper
  - `components/index` (note that this is currently exposed globally as `$dataviz`, for embedded components)

- `site.js` will contain:
  - `header.js`
  - `footer.js`
  - search code (once it lands in scripts)
  - `widgets/index`
  - `root-instances` (note that this is exposed globally too, for our local templates)

**Comment by ccurcanu** [comment]
https://github.com/EEA-Norway-Grants/dataviz/pull/388
