### ISSUE TITLE
projects: news filtering by current region

### ISSUE THREAD

**Issue by xlotlu** [EEA-Norway-Grants/dataviz#389]
news can now access `this.localfilters.region` (as long as they use the `Projects` mixin).
clicking on a region on the map triggers `handleFilterRegion`

**Comment by melish** [comment]
@rexalex @xlotlu 
Notes:
* when zoomed on a country (first level of zoom), show all project news in beneficiary state (reverse chronological order)
* when zoomed on a NUTS2 region, show all project news in the selected NUTS 2 and NUTS 3 (children of the selected NUTS2). If news list is empty (or < 3) then show news from nuts 0 and 1 levels as well.

**Comment by melish** [comment]
fixed in PR #422
