### ISSUE TITLE
each priority sector has its own icon

### ISSUE THREAD

**Issue by melish** [EEA-Norway-Grants/dataviz#39]
See http://eeagrants.org/What-we-do

The images should be used inside the pie chart (PS/PA), according to the selected sector

**Comment by xlotlu** [comment]
first try to get hold of the images in vector format, otherwise download them from the url.

either way, we should build a sprite the same way as flags, we just need to be careful with the name matching.

**Comment by melish** [comment]
Quote from FMO: "However the icons will be phased out soon, so we will replace or remove them at some point"

**Comment by melish** [comment]
EPS icons available on google drive
