### ISSUE TITLE
filter bar must reflect filters available to the current scenario

### ISSUE THREAD

**Issue by xlotlu** [EEA-Norway-Grants/dataviz#400]
filters that are not applicable to the current scenario should be either (to be decided): 
- dropped. they will neither be visible, nor perpetuate to another scenario. or
- preserved but grayed out. they shouln't react to direct removal, but be removed by the "Reset filters" button (?), and they should perpetuate to other scenarios.

this should also revert the bad fix in #306 

![out](https://user-images.githubusercontent.com/136097/30752599-745a6136-9fc5-11e7-8288-d6085a11e201.png)

**Comment by melish** [comment]
Customer said "dropped"
