### ISSUE TITLE
projects map: wrong country-level vs region-level totals

### ISSUE THREAD

**Issue by xlotlu** [EEA-Norway-Grants/dataviz#402]
See Romania: 289 + 92+84+105+23+56+27+48+117 = 841 != 854
Some of them might be ROZ*, but that still doesn't account for the entire difference.

**Comment by melish** [comment]
See also Croatia: 16 + 14 instead of 56

**Comment by xlotlu** [comment]
@melish see https://github.com/EEA-Norway-Grants/dataviz/issues/134#issuecomment-331507342

**Comment by melish** [comment]
HR04D shows 5 instead of 6

**Comment by melish** [comment]
Still missing: ROZZ, ROZZZ

**Comment by melish** [comment]
Maybe here is the right place to mention that Hungary shows 0 projects on the map when filtered by 
/projects/?fm=Norway+Grants&sector=Research+and+Scholarship

**Comment by xlotlu** [comment]
@melish I guess the Hungary issue was exposed by 40179aef8c1c05fb345096cb8081047c88a612c8 and it seems to be the same as under #404: see how ?fm=Norway+Grants&beneficiary=HU shows allocation data for "Research and Scholarship" but zero projects. taking care of this case in the code would be pretty awkward.

except that, this seems to be fully fixed now?
