### ISSUE TITLE
dropdown filters issues

### ISSUE THREAD

**Issue by xlotlu** [EEA-Norway-Grants/dataviz#403]
- [ ] the select element's border is invisible (on some browsers only (?))
- [ ] the select element's icon is invisible (on some browsers only (?))
- [ ] the first option should be right-aligned when the drop-down is right-aligned
- [ ] the placeholders should be right-aligned

**Comment by mihai-macaneata** [comment]
closed in 2588889b4724d13bfefd93d19fe29bc143887976   5d3a86e6fbc2701384b10cdc7b33f4ffb9b989d7
