### ISSUE TITLE
projects map: legend's color differs for beneficiaries

### ISSUE THREAD

**Issue by xlotlu** [EEA-Norway-Grants/dataviz#406]
Beneficiaries are grey in legend while white on the map.

(Note that user testing shows the white to be confusing, and they expect the regions to be grey, not the legend white.)

**Comment by xlotlu** [comment]
@melish: design decision needed: should the legend box be white, or should the beneficiaries be grey?

**Comment by melish** [comment]
Related remark:
Still show the DS legend if if you zoom in on a country.
* Shade the BS with the grey color from the legend (as it should be)
* Add the red circle to the ledgend with the text «Project count»

**Comment by melish** [comment]
fixed via #500
