### ISSUE TITLE
All country bar charts: numbers in legend don't update when filtering by self

### ISSUE THREAD

**Issue by xlotlu** [EEA-Norway-Grants/dataviz#408]
The legend always shows the total count for DPPs and dpps, regardless of filtering by a donor state or not.

User testing shows the expected behaviour is for the numbers to update along with the DS filter.

**Comment by melish** [comment]
JAS: As it is now, it only confuses the users as the PS/PA filter affects it but not the country filter.
If it cannot be easily changed then I’d recommend to remove it.

**Comment by melish** [comment]
![image](https://user-images.githubusercontent.com/1218168/31090843-c27f22e0-a7b1-11e7-8a2e-d2ed4d440b80.png)

**Comment by melish** [comment]
closed via #484
