### ISSUE TITLE
partners: Results: change number styling

### ISSUE THREAD

**Issue by xlotlu** [EEA-Norway-Grants/dataviz#409]
feedback shows the grants/Results look is preferred:

> Can we skip the blue box and just have the numbers look the same as for the results?
> You could use the blue colour from the heading text as the colour for the line.

note that approving this should close-wontfix #410

**Comment by melish** [comment]
Ok, remove blue box

**Comment by melish** [comment]
Also: Large numbers should be formatted as in the rest of the website (1 000 000)
