### ISSUE TITLE
partners: show only DPPs / dpps

### ISSUE THREAD

**Issue by xlotlu** [EEA-Norway-Grants/dataviz#411]
feedback shows one expects the map legend checkboxes to affect what the bar charts display
(as well as their legend to be clickable and result in DPP / dpp filtering)

**Comment by melish** [comment]
I see a point here - the number of dpp/promoters is much larger than the number of DPP/prg operators. 
Comparing countries by the number of DPP and programme operators would be easier - assuming the horizontal bars are resized

**Comment by melish** [comment]
Need to clarify first a comment from Johanna: "I expected the checkboxes for Show DPP and dpp not also have an effect on the filter"

**Comment by melish** [comment]
Confirmed: The checkboxes should only affect the map, not the other charts.
