### ISSUE TITLE
Find and repair lost styles

### ISSUE THREAD

**Issue by mihai-macaneata** [EEA-Norway-Grants/dataviz#427]

**Comment by melish** [comment]
home page footer on Internet Explorer
main menu underlined on prod server
search icon not aligned on IE

**Comment by mihai-macaneata** [comment]
main menu underlined on prod server (#436) is caused by the style tag containing the .dataviz styles appended in head after the two css files

**Comment by mihai-macaneata** [comment]
All issues left unchecked are happening because of styles clash in production mode
