### ISSUE TITLE
Project map: Stronger borders for the selected country/region when zooming in

### ISSUE THREAD

**Issue by melish** [EEA-Norway-Grants/dataviz#526]
![image](https://user-images.githubusercontent.com/1218168/32268781-079295e8-bef9-11e7-8e01-a2b3e5256ffa.png)

**Comment by xlotlu** [comment]
the parent region's border is stronger, but it's not visible any more because of the fill.

fixing this will requires that the parent regions always come on top, and stay visible while changing only their fill, and also make sure they don't capture mouse events.

**Comment by melish** [comment]
Alternative solution: try to highlight the selected country and/or region using background colours and transparency
