### ISSUE TITLE
Use normalize.css

### ISSUE THREAD

**Issue by xlotlu** [EEA-Norway-Grants/dataviz#63]
https://github.com/necolas/normalize.css

It should be npm installed and imported with ES6-like syntax in main.css.
Also remove this part https://github.com/EEA-Norway-Grants/dataviz/commit/817a101fa9c4016bdd646454dc5574b1e2b96f83

**Comment by mihai-macaneata** [comment]
Closed in f4d355b

**Comment by mihai-macaneata** [comment]
Solved in 6c3c702

**Comment by xlotlu** [comment]
As the description says:
- it needs to be imported in main.css. Doing it in .js causes it not to get included by the production build.
- remove the duplicate `svg:not(:root)` from main.

**Comment by mihai-macaneata** [comment]
Is the new implementation ok ? Can we close the ticket ?

**Comment by xlotlu** [comment]
there, that seems to be the preferred syntax.
works on dev, works on production, closed.
