### ISSUE TITLE
sectors visualisation: navigation between sectors and areas

### ISSUE THREAD

**Issue by xlotlu** [EEA-Norway-Grants/dataviz#7]
- some "back" button to navigate back from level 2
- keep displaying current sector, as shown in the design proposal

**Comment by mihai-macaneata** [comment]
I have added a reset method on click the parent element in the children legend, but the method is kind of rough since it removes and redraws the map

**Comment by xlotlu** [comment]
smoothen it then

**Comment by mihai-macaneata** [comment]
Should I add an animation to the map drawChart and drawMap methods ? or implement the same logic that we use for displaying children to display back the parents ?
