### ISSUE TITLE
PA filtering color bug

### ISSUE THREAD

**Issue by mihai-macaneata** [EEA-Norway-Grants/dataviz#87]
Clicking a PA right after filtering for a PA causes this:
![4dc2048c3b01fcba6d9eb7911e78bbff](https://cloud.githubusercontent.com/assets/12417029/26455357/a10f11f6-4172-11e7-8a4a-b30f6f3cbf82.png)

**Comment by xlotlu** [comment]
there's a race condition between rendering and highlighting. it's documented in the code:
[Sectors.vue#L602](https://github.com/EEA-Norway-Grants/dataviz/blob/ebd3b0f743d4a8105a4edd2e9b3338be202a8940/assets/js/components/Sectors.vue#L602), [Sectors.vue#L668](https://github.com/EEA-Norway-Grants/dataviz/blob/ebd3b0f743d4a8105a4edd2e9b3338be202a8940/assets/js/components/Sectors.vue#L668).

the solution is either wrapping each arc in a <g>, and setting the fill colour on it (low complexity, but complicates rendering code), or doing a custom tween (high complexity, doesn't touch rendering code). i lean towards the first option.
