### ISSUE TITLE
Fix tooltips

### ISSUE THREAD

**Issue by melish** [EEA-Norway-Grants/dataviz#90]
FM:
- positioned below
- less whitespace

Map:
- add gross amount when zoom level = Europe
- add "(Temporary)" text when zoom level = one country

Countries:
- left align figures
- Don't show FM when allocation is zero

**Comment by mihai-macaneata** [comment]
I think we should close this issue and add a new issue just for " add gross amount when zoom level = Europe " since it's the only task left and it's more a data issue than a tooltip issue since we don't have the needed data for it.
