### ISSUE TITLE
Funding map should allow drill down only for countries included in the current selection

### ISSUE THREAD

**Issue by melish** [EEA-Norway-Grants/dataviz#94]
Steps: click on PS 'Other'. Only 3 countries remaining in the Beneficiaries chart.
We should not be able to click on other countries in the map. 
There should be a different colour for filtered countries (dark gray, as in bar chart disabled)

**Comment by xlotlu** [comment]
starting map doesn't have data bound to it right now. needs some thinking.

**Comment by xlotlu** [comment]
duplicated under #109
